
const $=id=>document.getElementById(id);let token=localStorage.sw_token||"",B=null;
async function api(action,payload={}){let r=await fetch(APP_CONFIG.API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,token,payload})}),t=await r.text();if(t.trim().startsWith("<"))throw Error("API returned HTML. Check Apps Script deployment.");let j=JSON.parse(t);if(!j.ok)throw Error(j.error);return j.data}
function cacheSet(x){localStorage.sw_boot=JSON.stringify({at:Date.now(),data:x})}function cacheGet(){try{let x=JSON.parse(localStorage.sw_boot);return Date.now()-x.at<APP_CONFIG.CACHE_MINUTES*60000?x.data:null}catch(e){return null}}
async function login(){try{let d=await api("memberLogin",{phone:$("phone").value,password:$("pass").value});token=d.token;localStorage.sw_token=token;B={session:{kind:"member",member:d.member},modules:d.modules,access:d.access,dashboard:null,offices:[]};$("login").hidden=true;$("app").hidden=false;$("who").textContent=d.member.Name+" • "+(d.member.Designation||"Member");home();refreshApp()}catch(e){$("msg").innerHTML=`<div class=error>${e.message}</div>`}}
function logout(){localStorage.removeItem("sw_token");localStorage.removeItem("sw_boot");location.reload()}
async function refreshApp(){try{let d=await api("bootstrap");B=d;cacheSet(d);renderWho();home(true)}catch(e){console.warn(e)}}
function renderWho(){let m=B.session.member;$("who").textContent=m.Name+" • "+(m.Designation||"Member")}
function icon(k){let x={members:"👥",volunteers:"🙋",donations:"₹",goods_donations:"🎁",donors:"🤝",programs:"◎",projects:"▣",events:"◉",campaigns:"📣",beneficiaries:"❤",help_requests:"🆘",documents:"▤",certificates:"▧",meetings:"◫",notifications:"🔔",attendance:"✓",offices:"⌘",employees:"♟",receipts:"🧾",expenses:"₹",inventory:"▦"};return x[k]||"◆"}
function nav(active){["bhome","bmodules"].forEach(x=>$(x)?.classList.remove("active"));$(active)?.classList.add("active")}
function home(noRefresh){nav("bhome");let m=B.session.member,d=B.dashboard||{counts:{},recent:[]},quick=(B.modules||[]).slice(0,8);$("view").innerHTML=`<section class=hero><h2>नमस्ते, ${m.FirstName||m.Name}</h2><p>${m.Designation||""}</p><p>${m.OfficeID||m.Panchayat||m.District||""}</p><span class=status>${m.Status}</span></section><div class=sectiontitle><h3>त्वरित पहुँच</h3><span onclick=modules()>सभी देखें</span></div><div class=quick>${quick.map(x=>`<button class=q onclick="openModule('${x.ModuleKey}','${x.ModuleName}')"><i>${icon(x.ModuleKey)}</i><span>${x.ModuleName}</span></button>`).join("")}</div><div class=sectiontitle><h3>मेरी गतिविधि</h3></div><div class=kpis>${Object.entries(d.counts||{}).slice(0,6).map(([k,v])=>`<div class=kpi><b>${v}</b><small>${k}</small></div>`).join("")}</div><div class=sectiontitle><h3>नवीनतम अपडेट</h3></div><div class=cards>${(d.recent||[]).map(x=>`<div class=card><b>${x.Title||x.Message||"Notification"}</b><div class=meta>${x.Date||""}</div></div>`).join("")||"<div class=card>No new updates.</div>"}</div>`}
function modules(){nav("bmodules");let groups={};(B.modules||[]).forEach(m=>(groups[m.Group]??=[]).push(m));$("view").innerHTML=`<div class=searchbar><input id=ms placeholder="Search modules..." oninput=filterModules()></div><div id=mg>${Object.entries(groups).map(([g,a])=>`<section class=group><div class=groupname>${g}</div><div class=modulegrid>${a.map(x=>`<button class=module data-name="${x.ModuleName.toLowerCase()}" onclick="openModule('${x.ModuleKey}','${x.ModuleName}')"><i>${icon(x.ModuleKey)}</i><span>${x.ModuleName}</span></button>`).join("")}</div></section>`).join("")}</div>`}
function filterModules(){let q=$("ms").value.toLowerCase();document.querySelectorAll(".module").forEach(x=>x.style.display=x.dataset.name.includes(q)?"":"none")}
async function openModule(k,name){$("view").innerHTML="<div class=loading>Loading...</div>";try{let r=await api("list",{module:k});$("view").innerHTML=`<div class=toolbar><button class=back onclick=modules()>←</button><h3>${name}</h3>${can(k,"Add")?`<button class="btn g" onclick="quickAdd('${k}')">+ Add</button>`:""}</div><div class=cards>${r.map(x=>card(x,k)).join("")||"<div class=card>No records found.</div>"}</div>`}catch(e){$("view").innerHTML=`<div class=error>${e.message}</div>`}}
function card(x,k){let keys=Object.keys(x).filter(z=>x[z]).slice(0,7);return `<div class=card><h3>${x.Name||x.OfficeName||x.DonorName||x.ProjectName||x.Title||x[keys[0]]||"Record"}</h3>${keys.slice(1,6).map(z=>`<div class=meta><b>${z}:</b> ${x[z]}</div>`).join("")}${x.Status?`<span class="badge ${String(x.Status).toLowerCase()}">${x.Status}</span>`:""}</div>`}
function can(k,p){let a=(B.access||[]).find(x=>x.ModuleKey===k);return a&&String(a[p]).toLowerCase()==="true"}
function quickAdd(k){if(k==="donations")return addDonation();alert("Add form for "+k+" is controlled by your designation and module schema.")}
async function addDonation(){let DonorName=prompt("Donor name");if(!DonorName)return;let Amount=prompt("Amount");if(!Amount)return;try{let d=await api("createDonation",{DonorName,Amount,PaymentMode:"Cash",Purpose:"General Donation"});alert("Saved. Receipt: "+d.ReceiptNo);openModule("donations","Donations")}catch(e){alert(e.message)}}
function offices(){let r=B.offices||[];$("view").innerHTML=`<div class=toolbar><h3>Office & Lower Registers</h3></div><div class=cards>${r.map(o=>`<div class=card><h3>${o.OfficeName}</h3><div class=meta>${o.OfficeType} • ${[o.Block,o.District,o.State].filter(Boolean).join(", ")}</div><p><b>${o.MemberCount}</b> active members • <b>${o.LowerOfficeCount}</b> lower offices</p><button class="btn g" onclick="alert('Register: ${o.OfficeID}')">Open Register</button></div>`).join("")}</div>`}
function profile(){let m=B.session.member;$("view").innerHTML=`<div class=card><h3>${m.Name}</h3><p>${m.Designation||""}</p><p>${m.MemberID}</p><p>${m.Mobile}</p><span class=badge>${m.Status}</span><div class=actions><button class=btn onclick=changePw()>Change Password</button></div></div>`}
async function changePw(){let oldPassword=prompt("Current password");if(!oldPassword)return;let newPassword=prompt("New password");if(!newPassword)return;try{await api("changePassword",{oldPassword,newPassword});alert("Password changed")}catch(e){alert(e.message)}}
(async()=>{if(token){let c=cacheGet();if(c){B=c;$("login").hidden=true;$("app").hidden=false;renderWho();home()}try{B=await api("bootstrap");cacheSet(B);$("login").hidden=true;$("app").hidden=false;renderWho();home()}catch(e){if(!B)logout()}}})();
