
const $=x=>document.getElementById(x);let token=localStorage.swToken||"",S=null,A=[];
async function api(action,payload={}){const r=await fetch(SEWANGAN_CONFIG.API_URL,{method:"POST",headers:{"Content-Type":"text/plain"},body:JSON.stringify({action,token,payload})});const j=await r.json();if(!j.ok)throw Error(j.error);return j.data}
async function login(){try{const d=await api("memberLogin",{phone:$("phone").value,password:$("pass").value});token=d.token;localStorage.swToken=token;S=d;A=d.access;start()}catch(e){$("msg").textContent=e.message}}
function logout(){localStorage.removeItem("swToken");location.reload()}function perm(m,p="View"){const a=A.find(x=>x.ModuleKey===m);return a&&String(a[p]).toLowerCase()==="true"}
const labels={dashboard:"Dashboard",offices:"Office Registers",members:"Members",volunteers:"Volunteers",donations:"Donations",goodsdonations:"Goods Donations",donors:"Donors",programs:"Programs",projects:"Projects",events:"Events",campaigns:"Campaigns",beneficiaries:"Beneficiaries",helprequests:"Help Requests",charityactivities:"Charity Activities",attendance:"Attendance",documents:"Documents",certificates:"Certificates",meetings:"Meetings",notifications:"Notifications",reports:"Reports"};
function start(){$("login").classList.add("hidden");$("app").classList.remove("hidden");$("who").textContent=S.member.Name+" • "+(S.member.Designation||"Member");$("nav").innerHTML=A.filter(x=>String(x.View).toLowerCase()==="true").map(x=>`<button onclick="openM('${x.ModuleKey}')">${labels[x.ModuleKey]||x.ModuleKey}</button>`).join("");openM("dashboard")}
async function openM(m){if(m==="dashboard")return dash();if(m==="offices")return offices();return list(m)}
function dash(){const m=S.member;$("view").innerHTML=`<div class="card hero"><h2>Welcome, ${m.Name}</h2><p>${m.Designation||""} • ${m.Panchayat||m.Block||m.District||m.State||""}</p><span class="status ${String(m.Status).toLowerCase()}">${m.Status}</span></div><div class=grid>${A.filter(x=>String(x.View).toLowerCase()==="true"&&x.ModuleKey!=="dashboard").slice(0,8).map(x=>`<div class=card><h3>${labels[x.ModuleKey]||x.ModuleKey}</h3><p>${x.Scope||"Own"} access</p><button onclick="openM('${x.ModuleKey}')">Open</button></div>`).join("")}</div>`}
async function offices(){const r=await api("officeCards");$("view").innerHTML=`<h2>Office & Lower-Level Registers</h2><div class=grid>${r.map(o=>`<div class="card office"><h3>${o.OfficeName}</h3><p><b>${o.OfficeType}</b></p><p>${[o.Block,o.District,o.State].filter(Boolean).join(", ")}</p><p>Active members: <b>${o.MemberCount}</b> • Lower offices: <b>${o.LowerOfficeCount}</b></p><button onclick="alert('Office register: ${o.OfficeID}')">View Register</button></div>`).join("")}</div>`}
async function list(m){const r=await api("list",{module:m});let extra="";if(m==="volunteers"&&S.member.DesignationID==="DES-AM"&&perm(m,"Add"))extra=`<button onclick="addVolunteer()">+ Add Volunteer</button>`;if(m==="donations"&&perm(m,"Add"))extra+=` <button class=green onclick="addDonation()">+ Add Donation</button>`;$("view").innerHTML=`<div class=toolbar><h2>${labels[m]||m}</h2>${extra}</div><div class=grid>${r.map(x=>`<div class="card member">${Object.entries(x).slice(0,7).map(([k,v])=>`<div><b>${k}:</b> ${v||""}</div>`).join("")}</div>`).join("")||"<div class=card>No records.</div>"}</div>`}
async function addVolunteer(){const name=prompt("Volunteer name");if(!name)return;const mobile=prompt("Mobile number")||"";try{await api("addVolunteer",{name,mobile});alert("Volunteer request added");openM("volunteers")}catch(e){alert(e.message)}}
async function addDonation(){const donorName=prompt("Donor name");if(!donorName)return;const amount=prompt("Amount");try{const d=await api("createDonation",{donorName,amount,paymentMode:"Cash",purpose:"General Donation"});alert("Donation saved. Receipt: "+d.receiptNo);openM("donations")}catch(e){alert(e.message)}}
async function changePw(){const oldPassword=prompt("Current password");if(!oldPassword)return;const newPassword=prompt("New password (minimum 6 characters)");if(!newPassword)return;try{await api("changePassword",{oldPassword,newPassword});alert("Password changed")}catch(e){alert(e.message)}}
(async()=>{if(token)try{S=await api("session");A=S.access||[];start()}catch(e){localStorage.removeItem("swToken")}})();
