
const SS=SpreadsheetApp.getActive(), SESSION_HOURS=12, SHEETS={"users": "Users", "roles": "Roles", "membertypes": "MemberTypes", "members": "Members", "membershipapplications": "MembershipApplications", "employees": "Employees", "employeedocuments": "EmployeeDocuments", "termsconditions": "TermsConditions", "volunteers": "Volunteers", "beneficiaries": "Beneficiaries", "helprequests": "HelpRequests", "charityactivities": "CharityActivities", "donors": "Donors", "receipts": "Receipts", "donations": "Donations", "goodsdonations": "GoodsDonations", "donationcollection": "DonationCollection", "offlinecash": "OfflineCash", "receiptblocks": "ReceiptBlocks", "fundraising": "Fundraising", "programs": "Programs", "projects": "Projects", "events": "Events", "campaigns": "Campaigns", "attendance": "Attendance", "leave": "Leave", "accounts": "Accounts", "transactions": "Transactions", "cashbook": "CashBook", "bankbook": "BankBook", "ledger": "Ledger", "payments": "Payments", "vouchers": "Vouchers", "expenses": "Expenses", "inventory": "Inventory", "inventorymovements": "InventoryMovements", "purchases": "Purchases", "vendors": "Vendors", "assets": "Assets", "documents": "Documents", "letters": "Letters", "dispatchregister": "DispatchRegister", "certificates": "Certificates", "meetings": "Meetings", "notifications": "Notifications"};
function out(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function sh(n){const s=SS.getSheetByName(n);if(!s)throw Error("Missing sheet: "+n);return s}
function rows(n){const v=sh(n).getDataRange().getDisplayValues();if(v.length<2)return[];const h=v[0];return v.slice(1).filter(r=>r.some(x=>x!=="")).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]])))}
function append(n,o){const s=sh(n),h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0];s.appendRow(h.map(k=>o[k]??""));return o}
function save(n,o){const s=sh(n),v=s.getDataRange().getValues(),h=v[0],id=String(o[h[0]]||"");if(!id)throw Error(h[0]+" is required");let rr=0;for(let i=1;i<v.length;i++)if(String(v[i][0])===id){rr=i+1;break}const a=h.map(k=>o[k]??"");rr?s.getRange(rr,1,1,h.length).setValues([a]):s.appendRow(a);return o}
function del(n,id){const s=sh(n),v=s.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(id)){s.deleteRow(i+1);return true}return false}
function kv(n){return Object.fromEntries(rows(n).map(r=>[r.Key||r.SettingKey,r.Value??r.SettingValue]))}
function saveKV(n,a){const s=sh(n),v=s.getDataRange().getValues();a.forEach(x=>{let f=0;for(let i=1;i<v.length;i++)if(String(v[i][0])===x.key){s.getRange(i+1,2).setValue(x.value);f=1;break}if(!f)s.appendRow([x.key,x.value,"",""])});return true}
function audit(u,a,m,id,d){append("AuditLog",{LogID:"LOG-"+Utilities.getUuid().slice(0,8),DateTime:new Date(),UserID:u||"PUBLIC",Action:a,Module:m,RecordID:id||"",Details:d||""})}
function roleName(id){return(rows("Roles").find(x=>x.RoleID===id)||{}).RoleName||""}
function access(id){const a={};rows("RoleAccess").filter(x=>x.RoleID===id).forEach(r=>{a[r.ModuleKey]={};["View","Add","Edit","Delete","Approve","Print","Export"].forEach(k=>a[r.ModuleKey][k]=String(r[k]).toLowerCase()==="true")});return a}
function login(p){const u=rows("Users").find(x=>(x.Email===p.user||x.UserID===p.user)&&x.Status!=="Inactive");if(!u||String(u.PasswordHash)!==String(p.password))throw Error("Invalid login");const t=Utilities.getUuid(),d={user:{id:u.UserID,name:u.Name,roleId:u.RoleID,role:roleName(u.RoleID)},access:access(u.RoleID)};CacheService.getScriptCache().put("S_"+t,JSON.stringify(d),SESSION_HOURS*3600);return{token:t,...d}}
function sess(t){const x=CacheService.getScriptCache().get("S_"+t);if(!x)throw Error("Session expired");return JSON.parse(x)}
function auth(s,m,p){if(s.user.role==="Super Admin")return; if(!(s.access[m]||{})[p])throw Error("Access denied: "+p+" "+m)}
function nextNo(type){const s=sh("Numbering"),v=s.getDataRange().getValues();for(let i=1;i<v.length;i++)if(v[i][0]===type){const n=Number(v[i][3]||1),d=Number(v[i][4]||6),no=v[i][1]+"/"+v[i][2]+"/"+String(n).padStart(d,"0");s.getRange(i+1,4).setValue(n+1);return no}return Utilities.getUuid()}
function nextReceipt(){const l=LockService.getScriptLock();l.waitLock(30000);try{const s=sh("ReceiptSequence"),r=s.getRange(2,1,1,6).getValues()[0],n=Number(r[2]||1),d=Number(r[3]||6),no=String(r[1]||"SDR")+"/"+String(r[0]||"2627")+"/"+String(n).padStart(d,"0");s.getRange(2,3).setValue(n+1);s.getRange(2,5).setValue(no);s.getRange(2,6).setValue(new Date());return no}finally{l.releaseLock()}}
function donor(p){let d=rows("Donors").find(x=>x.Mobile&&x.Mobile===String(p.mobile));if(d)return d.DonorID;const id="D-"+Utilities.getUuid().slice(0,8).toUpperCase();append("Donors",{DonorID:id,Name:p.name,Mobile:p.mobile,Email:p.email,Address:p.address,Status:"Active"});return id}
function publicJoin(p){const id="APP-"+Utilities.getUuid().slice(0,8).toUpperCase(),free=p.type==="Volunteer";append("MembershipApplications",{ApplicationID:id,Date:new Date(),MemberType:p.type,Name:p.name,Mobile:p.mobile,Email:p.email,Address:p.address,District:p.district,State:p.state,Pin:p.pin,Amount:free?0:p.amount||"",PaymentMode:p.paymentMode||"",TransactionNo:p.transactionNo||"",PaymentProofURL:p.paymentProofURL||"",PaymentStatus:free?"Not Required":"Pending",ApplicationStatus:"Pending",Source:"Sewangan Web App"});audit("PUBLIC","CREATE","membershipapplications",id,"Join application");return{applicationId:id,paymentRequired:!free}}
function publicDonation(p){const did=donor(p),id="DON-"+Utilities.getUuid().slice(0,8).toUpperCase(),no=nextReceipt(),now=new Date();append("Donations",{DonationID:id,ReceiptNo:no,Date:now,DonorID:did,DonorName:p.name,Amount:p.amount,PaymentMode:"UPI",TransactionNo:p.transactionNo,PaymentProofURL:p.paymentProofURL||"",Purpose:p.purpose,ReceivedAt:"Online",Source:"Sewangan Web App",SyncStatus:"Synced",VerificationStatus:"Pending",Status:"Pending Verification"});append("Receipts",{ReceiptNo:no,DateTime:now,DonationType:"Money",DonationID:id,DonorID:did,DonorName:p.name,Amount:p.amount,PaymentMode:"UPI",TransactionNo:p.transactionNo,PaymentProofURL:p.paymentProofURL||"",Purpose:p.purpose,ReceivedAt:"Online",Source:"Sewangan Web App",SyncStatus:"Synced",Status:"Pending Verification"});audit("PUBLIC","CREATE","donations",id,no);return{receiptNo:no,donationId:id}}
function publicGoods(p){const did=donor(p),id="GD-"+Utilities.getUuid().slice(0,8).toUpperCase(),no=nextReceipt(),now=new Date();append("GoodsDonations",{GoodsDonationID:id,ReceiptNo:no,Date:now,DonorID:did,DonorName:p.name,ItemDetails:p.items,Quantity:p.qty,Unit:p.unit,Condition:p.condition,EstimatedValue:p.value,CollectionMode:p.collection,PickupAddress:p.address,ReceivedAt:p.collection,Source:"Sewangan Web App",InventoryPosted:"No",Status:"Registered"});append("Receipts",{ReceiptNo:no,DateTime:now,DonationType:"Goods",DonationID:id,DonorID:did,DonorName:p.name,EstimatedValue:p.value,Purpose:"Goods Donation",ReceivedAt:p.collection,Source:"Sewangan Web App",SyncStatus:"Synced",Status:"Issued"});audit("PUBLIC","CREATE","goodsdonations",id,no);return{receiptNo:no}}
function dashboard(){return{Members:rows("Members").length,Employees:rows("Employees").length,Volunteers:rows("Volunteers").length,Donors:rows("Donors").length,Beneficiaries:rows("Beneficiaries").length,Donations:rows("Donations").length,Projects:rows("Projects").length,PendingHelp:rows("HelpRequests").filter(x=>x.Status==="Pending").length}}
function report(p){const n=SHEETS[p.module];if(!n)throw Error("Unknown report module");let r=rows(n);if(p.from)r=r.filter(x=>!x.Date||x.Date>=p.from);if(p.to)r=r.filter(x=>!x.Date||x.Date<=p.to);return r}
function doGet(){return out({ok:true,name:"Sewangan ERP API"})}
function doPost(e){try{const q=JSON.parse(e.postData.contents||"{}"),a=q.action,p=q.payload||{},pub=["login","publicSettings","publicJoin","publicDonation","publicGoods","publicReceipt"];let s=null;if(!pub.includes(a))s=sess(q.token);let d;
if(a==="login")d=login(p);
else if(a==="session")d=s;
else if(a==="publicSettings")d={organization:kv("Organization"),settings:kv("Settings"),memberTypes:rows("MemberTypes")};
else if(a==="publicJoin")d=publicJoin(p);
else if(a==="publicDonation")d=publicDonation(p);
else if(a==="publicGoods")d=publicGoods(p);
else if(a==="publicReceipt"){const r=rows("Receipts").find(x=>x.ReceiptNo===p.receiptNo);if(!r)throw Error("Receipt not found");d={organization:kv("Organization"),receipt:r,donor:rows("Donors").find(x=>x.DonorID===r.DonorID)||{},goods:rows("GoodsDonations").find(x=>x.ReceiptNo===p.receiptNo)||{}}}
else if(a==="dashboard")d=dashboard();
else if(a==="list"){auth(s,p.module,"View");d=rows(SHEETS[p.module])}
else if(a==="save"){auth(s,p.module,p.isEdit?"Edit":"Add");d=save(SHEETS[p.module],p.record);audit(s.user.id,p.isEdit?"EDIT":"ADD",p.module,Object.values(p.record)[0],"")}
else if(a==="delete"){auth(s,p.module,"Delete");d=del(SHEETS[p.module],p.id);audit(s.user.id,"DELETE",p.module,p.id,"")}
else if(a==="approve"){auth(s,p.module,"Approve");const n=SHEETS[p.module],r=rows(n).find(x=>String(Object.values(x)[0])===String(p.id));if(!r)throw Error("Record not found");const sk=Object.keys(r).find(k=>/status/i.test(k));if(sk)r[sk]=p.status||"Approved";d=save(n,r);audit(s.user.id,"APPROVE",p.module,p.id,p.status||"Approved")}
else if(a==="getOrganization")d=rows("Organization");
else if(a==="saveOrganization"){auth(s,"organization","Edit");d=saveKV("Organization",p.rows)}
else if(a==="getSettings")d=rows("Settings");
else if(a==="saveSettings"){auth(s,"settings","Edit");d=saveKV("Settings",p.rows)}
else if(a==="roleAccess"){auth(s,"roles","View");d=rows("RoleAccess").filter(x=>x.RoleID===p.roleId)}
else if(a==="saveRoleAccess"){auth(s,"roles","Edit");const rs=sh("RoleAccess"),old=rows("RoleAccess").filter(x=>x.RoleID!==p.roleId);rs.clearContents();rs.appendRow(["RoleID","ModuleKey","View","Add","Edit","Delete","Approve","Print","Export"]);old.forEach(r=>rs.appendRow([r.RoleID,r.ModuleKey,r.View,r.Add,r.Edit,r.Delete,r.Approve,r.Print,r.Export]));p.rows.forEach(r=>rs.appendRow([p.roleId,r.ModuleKey,!!r.View,!!r.Add,!!r.Edit,!!r.Delete,!!r.Approve,!!r.Print,!!r.Export]));d=true}
else if(a==="report"){auth(s,p.module,"Export");d=report(p)}
else throw Error("Unknown action");
return out({ok:true,data:d})}catch(err){return out({ok:false,error:String(err.message||err)})}}
